# config.toml contient :
# - le thème de l'application
# - une instruction pour cacher la sidebar

[ui]
hideSidebarNav = true

[theme]
primaryColor="#3CCDBC"
backgroundColor="#39342E"
secondaryBackgroundColor="#564D44"
textColor="#FAFAFA"